services:
  - type: web
    name: export-api
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        value: "8080"
    buildCommand: docker build -t export-api .
    startCommand: docker run -p $PORT:8080 export-api
